### ISSUE TITLE
[Todo] Discord Integration

### ISSUE THREAD

**Issue by scryptonite** [TalimaVale/BeastieBot#10]
- [ ] Beastie should assign the appropriate roles in the Discord server when it can verify that they are following the broadcaster's channel.
- [ ] Beastie should announce when the stream goes live.
  - *Idea*) Beastie should also edit stream announcements with a link to the VOD once stream has ended.
- [ ] Some commands supported in the Twitch chatroom should also be supported in the Discord (possibly whitelisted per text channel to minimize chat clutter)

----------
EDIT:

**npm library choices**
  - <code>npm i --save <a href="https://www.npmjs.com/package/discord.js">discord.js</a></code> &mdash; [:octocat: source code](https://github.com/hydrabolt/discord.js)
  - <code>npm i --save <a href="https://www.npmjs.com/package/discord.io">discord.io</a></code> &mdash; [:octocat: source code](https://github.com/izy521/discord.io)
