### ISSUE TITLE
[Todo] Revlo integration

### ISSUE THREAD

**Issue by scryptonite** [TalimaVale/BeastieBot#11]
- [ ] Support handling reward redemptions
  - [ ] End of Stream Shoutout
  - [ ] Make It Rain
  - [ ] New Quote?
  - [ ] Team Wall Name Boost
  - [ ] Wheel Of Awesomeness Spin (requires that Beastie has a stream overlay #12)

Revlo API Documentation ➡️  https://github.com/teamrevlo/revloapi

**Comment by scryptonite** [comment]
Closing this issue.
> [The \[Team Revlo\] Adventure Comes to an End.](https://blog.revlo.co/the-adventure-comes-to-an-end-fa03f7fab84e)

**Comment by benwurth** [comment]
😢
